# Generated by Django 6.0.2 on 2026-02-26 03:00

import apps.diplomas.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to=apps.diplomas.models.diploma_upload_path)),
                ('tipo_archivo', models.CharField(max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('error_envio', models.TextField(blank=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diploma', to='courses.courseregistration')),
            ],
            options={
                'db_table': 'diplomas',
            },
        ),
    ]
