# Generated by Django 6.0.2 on 2026-02-26 03:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300, verbose_name='Título del curso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('instructores', models.CharField(blank=True, max_length=500, verbose_name='Instructores')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'courses',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CourseFormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=300, verbose_name='Etiqueta del campo')),
                ('tipo', models.CharField(choices=[('short_text', 'Texto corto'), ('long_text', 'Texto largo'), ('email', 'Correo electrónico'), ('number', 'Número'), ('select', 'Menú desplegable'), ('radio', 'Opción única'), ('checkbox', 'Selección múltiple'), ('date', 'Fecha'), ('time', 'Hora'), ('datetime', 'Fecha y hora')], max_length=20, verbose_name='Tipo de campo')),
                ('obligatorio', models.BooleanField(default=False, verbose_name='Campo obligatorio')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activo', models.BooleanField(default=True)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('ayuda', models.CharField(blank=True, max_length=300, verbose_name='Texto de ayuda')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='courses.course')),
            ],
            options={
                'verbose_name': 'Campo del formulario',
                'verbose_name_plural': 'Campos del formulario',
                'db_table': 'course_form_fields',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_participante', models.EmailField(max_length=254, verbose_name='Correo del participante')),
                ('nombre_participante', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False, verbose_name='Completó el curso')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('diploma_enviado', models.BooleanField(default=False)),
                ('fecha_diploma', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.course')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'course_registrations',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('course', 'email_participante')},
            },
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=200, verbose_name='Valor')),
                ('etiqueta', models.CharField(max_length=200, verbose_name='Etiqueta')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.courseformfield')),
            ],
            options={
                'verbose_name': 'Opción de campo',
                'verbose_name_plural': 'Opciones de campo',
                'db_table': 'field_options',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_texto', models.TextField(blank=True)),
                ('valor_multiple', models.JSONField(blank=True, null=True)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courseformfield')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.courseregistration')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'registration_answers',
            },
        ),
    ]
