# Generated by Django 4.2.11 on 2026-06-08 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_base_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Plantilla', 'verbose_name_plural': 'Plantillas'},
        ),
        migrations.AlterModelOptions(
            name='courseregistration',
            options={'ordering': ['-fecha_inscripcion']},
        ),
        migrations.AlterModelOptions(
            name='fieldoption',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='registrationanswer',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='course',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructores',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='titulo',
            field=models.CharField(max_length=300, verbose_name='Titulo de la plantilla'),
        ),
        migrations.AlterField(
            model_name='courseformfield',
            name='ayuda',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='courseformfield',
            name='label',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='courseformfield',
            name='obligatorio',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='courseformfield',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseformfield',
            name='tipo',
            field=models.CharField(choices=[('short_text', 'Texto corto'), ('long_text', 'Texto largo'), ('email', 'Correo electronico'), ('number', 'Numero'), ('select', 'Menu desplegable'), ('radio', 'Opcion unica'), ('checkbox', 'Seleccion multiple'), ('date', 'Fecha'), ('time', 'Hora'), ('datetime', 'Fecha y hora')], max_length=20),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='email_participante',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='etiqueta',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='valor',
            field=models.CharField(max_length=200),
        ),
    ]
