# Generated by Django 4.2.11 on 2026-06-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
