# Generated by Django 4.2.11 on 2026-06-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_archivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='curso_archivado',
            field=models.BooleanField(default=False),
        ),
    ]
